

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace strKey_Shader
{
	namespace Graphics
	{
		STRKEY BuildingStructure = "BuildingStructure.json";
		STRKEY SCUnitGround = "SCUnitGround.json";
		STRKEY Tilemap_SC = "Tilemap_SC.json";
		STRKEY Mineral = "Mineral.json";
		STRKEY VespineGeyser = "VespineGeyser.json";
	};
	namespace Compute
	{
		STRKEY S_C_ParticleRainDrop = "S_C_ParticleRainDrop.json";
		STRKEY S_C_SCMapLoader = "S_C_SCMapLoader.json";
	};
}