

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace strKey_Com
{
	STRKEY cCom_Renderer_TilemapSC = "cCom_Renderer_TilemapSC";
	STRKEY cScript_CameraMove = "cScript_CameraMove";
	STRKEY cScript_MainCamSC_InGame = "cScript_MainCamSC_InGame";
	STRKEY cScript_Mineral = "cScript_Mineral";
	STRKEY cScript_MouseCursor = "cScript_MouseCursor";
	STRKEY cScript_SCEntity = "cScript_SCEntity";
	STRKEY cScript_SCUnitVital = "cScript_SCUnitVital";
	STRKEY cScript_TestObj = "cScript_TestObj";
	STRKEY cScript_Vespene = "cScript_Vespene";
	STRKEY cScript_VespeneSmoke = "cScript_VespeneSmoke";
}
