
#pragma once

#include <string_view>

//This Code is Automatically generated by CodeGenerator.exe


namespace TEXTURE
{
	enum class Idx
	{
		BEHEADED,
		BEHEADED_N,
		CORSAIR,
		DEFAULT,
		FIGHTER,
		HOS,
		HOS,
		LINK,
		MARINE,
		TILE,
		TRILOB_REAVER_,
		NOISE_01,
		END
	};
	constexpr const std::string_view arrKey[] = 
	{
		"beheaded.png",
		"beheaded_n.png",
		"corsair.bmp",
		"Default.png",
		"Fighter.bmp",
		"HOS.bmp",
		"HOS.png",
		"link.png",
		"marine.bmp",
		"TILE.bmp",
		"trilob(Reaver).bmp",
		"noise/noise_01.png",
	};
}
