
#pragma once

//This Code is Automatically generated by CodeGenerator.exe


#include <string>
#include <string_view>


namespace SCRIPTS
{
constexpr const std::string_view BULLET = "CScript_Bullet.h";
constexpr const std::string_view CAMERAMOVE = "CScript_CameraMove.h";
constexpr const std::string_view MARINE = "CScript_Marine.h";
constexpr const std::string_view MOUSECURSOR = "CScript_MouseCursor.h";
constexpr const std::string_view SCGROUNDUNITFSM = "CScript_SCGroundUnitFSM.h";
constexpr const std::string_view TESTOBJ = "CScript_TestObj.h";
}