
#pragma once

//This Code is Automatically generated by CodeGenerator.exe

namespace SCRIPTS
{
	constexpr const char* BULLET = "CScript_Bullet.h";
	constexpr const char* CAMERAMOVE = "CScript_CameraMove.h";
	constexpr const char* TESTOBJ = "CScript_TestObj.h";
	constexpr const char* DEBUG = "CScript_Debug.h";
	constexpr const char* PLAYER = "CScript_Player.h";
	constexpr const char* MOUSECURSOR = "CScript_MouseCursor.h";
}