
#pragma once

#include <string_view>

//This Code is Automatically generated by CodeGenerator.exe


namespace TEXTURE
{
std::string_view BEHEADED = "beheaded.png";
std::string_view BEHEADED_N = "beheaded_n.png";
std::string_view CORSAIR = "corsair.bmp";
std::string_view DEFAULT = "Default.png";
std::string_view FIGHTER = "Fighter.bmp";
std::string_view HOS = "HOS.bmp";
std::string_view HOS = "HOS.png";
std::string_view LINK = "link.png";
std::string_view MARINE = "marine.bmp";
namespace NOISE
{
std::string_view NOISE_01 = "noise\noise_01.png";
}
std::string_view TILE = "TILE.bmp";
std::string_view TRILOB(REAVER) = "trilob(Reaver).bmp";