
#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


namespace strKey_SHADER
{
	namespace GRAPHICS
	{
		STRKEY BUILDINGSTRUCTURE = "BuildingStructure.json";
		STRKEY DEBUG = "Debug.json";
		STRKEY MINERAL = "Mineral.json";
		STRKEY PARTICLE = "Particle.json";
		STRKEY SCUNITGROUND = "SCUnitGround.json";
		STRKEY STD2D = "STD2D.json";
		STRKEY STD2DLIGHT = "STD2DLight.json";
		STRKEY TEST = "Test.json";
		STRKEY TILEMAPATLAS = "TilemapAtlas.json";
		STRKEY TILEMAPCOMPLETE = "TilemapComplete.json";
	}

	namespace COMPUTE
	{
		STRKEY _INITALIZE = "S_C_Initalize.json";
		STRKEY _PARTICLEBASIC = "S_C_ParticleBasic.json";
		STRKEY _PARTICLERAINDROP = "S_C_ParticleRainDrop.json";
		STRKEY _SCMAPLOADER = "S_C_SCMapLoader.json";
		STRKEY _SETCOLOR = "S_C_SetColor.json";
	}
}
