

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr inline const char*
#endif



namespace strKey_Shader
{
	STRKEY BuildingStructure = "BuildingStructure.json";
	STRKEY SCUnitGround = "SCUnitGround.json";
	STRKEY Tilemap_SC = "Tilemap_SC.json";
	STRKEY Mineral = "Mineral.json";
	STRKEY VespineGeyser = "VespineGeyser.json";
}