
#pragma once

//This Code is Automatically generated by CodeGenerator.exe


#include <Engine/define.h>

namespace strKey_SCRIPTS
{
	STRKEY FSM_MOVE_GROUND = "CScript_FSM_Move_Ground";
	STRKEY CAMERAMOVE = "CScript_CameraMove";
	STRKEY MOUSECURSOR = "CScript_MouseCursor";
	STRKEY FSM_ATTACK = "CScript_FSM_Attack";
	STRKEY FSM_ATTACK_BEGINEND = "CScript_FSM_Attack_BeginEnd";
	STRKEY FSM_DEATH = "CScript_FSM_Death";
	STRKEY FSM_IDLE = "CScript_FSM_Idle";
	STRKEY FSM_MOVE_HOVER = "CScript_FSM_Move_Hover";
	STRKEY SCENTITY = "CScript_SCEntity";
	STRKEY SCUNITVITAL = "CScript_SCUnitVital";
	STRKEY TESTOBJ = "CScript_TestObj";
}