

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr inline const char*
#endif



namespace strKey_Texture
{
	STRKEY beheaded = "beheaded.png";
	STRKEY beheaded_n = "beheaded_n.png";
	STRKEY Default = "Default.png";
	STRKEY Fighter = "Fighter.bmp";
	STRKEY HOS = "HOS.bmp";
	STRKEY HOS = "HOS.png";
	STRKEY link = "link.png";
	STRKEY TILE = "TILE.bmp";
	namespace NOISE
	{
		STRKEY noise_01 = "noise/noise_01.png";
	}

	namespace SC
	{
		namespace BULLET
		{
			STRKEY BlastScan = "Bullet/BlastScan.bmp";
			STRKEY Circle14 = "Bullet/Circle14.bmp";
			STRKEY DragBull = "Bullet/DragBull.bmp";
			STRKEY EPBBul = "Bullet/EPBBul.bmp";
			STRKEY EPHFile_Unknown_ = "Bullet/EPHFile(Unknown).bmp";
			STRKEY ephFire_Unknown_ = "Bullet/ephFire(Unknown).bmp";
			STRKEY Explo1 = "Bullet/Explo1.bmp";
			STRKEY EYCBull_Yamato_ = "Bullet/EYCBull(Yamato).bmp";
			STRKEY Gemini = "Bullet/Gemini.bmp";
			STRKEY Grenades = "Bullet/Grenades.bmp";
			STRKEY HKS = "Bullet/HKS.bmp";
			STRKEY Missile = "Bullet/Missile.bmp";
			STRKEY Parasite = "Bullet/Parasite.bmp";
			STRKEY PRRIPHIT = "Bullet/PRRIPHIT.bmp";
			STRKEY PSIBeam = "Bullet/PSIBeam.bmp";
			STRKEY PSpark_Scout_ = "Bullet/PSpark(Scout).bmp";
			STRKEY SCVSpark = "Bullet/SCVSpark.bmp";
			STRKEY ShockBomb = "Bullet/ShockBomb.bmp";
			STRKEY smmissle_Valkirye_ = "Bullet/smmissle(Valkirye).bmp";
			STRKEY Spike_Lurker_ = "Bullet/Spike(Lurker).bmp";
			STRKEY Spore2 = "Bullet/Spore2.bmp";
			STRKEY Spores_Mutalisk_ = "Bullet/Spores(Mutalisk).bmp";
			STRKEY Squib1 = "Bullet/Squib1.bmp";
			STRKEY Squip2 = "Bullet/Squip2.bmp";
			STRKEY Tentacle_Sunken_ = "Bullet/Tentacle(Sunken).bmp";
			STRKEY TSpark_TerranSpark_ = "Bullet/TSpark(TerranSpark).bmp";
			STRKEY ZSpark_ZergSpark_ = "Bullet/ZSpark(ZergSpark).bmp";
		}

		namespace CMDBUTTONS
		{
			STRKEY cmdicons = "CmdButtons/cmdicons.bmp";
			STRKEY pcmdbtns = "CmdButtons/pcmdbtns.bmp";
			STRKEY tcmdbtns = "CmdButtons/tcmdbtns.bmp";
			STRKEY zcmdbtns = "CmdButtons/zcmdbtns.bmp";
		}

		namespace NEUTRAL
		{
			STRKEY gasorb = "Neutral/gasorb.bmp";
			STRKEY gassac = "Neutral/gassac.bmp";
			STRKEY gastank = "Neutral/gastank.bmp";
			STRKEY Generate_Generator_ = "Neutral/Generate(Generator).bmp";
			STRKEY geyser = "Neutral/geyser.bmp";
			STRKEY geyshad = "Neutral/geyshad.bmp";
			STRKEY min01 = "Neutral/min01.bmp";
			STRKEY min01sha = "Neutral/min01sha.bmp";
			STRKEY min02 = "Neutral/min02.bmp";
			STRKEY min02sha = "Neutral/min02sha.bmp";
			STRKEY min03 = "Neutral/min03.bmp";
			STRKEY min03sha = "Neutral/min03sha.bmp";
		}

		namespace PROTOSS
		{
			STRKEY arbiter = "Protoss/arbiter.bmp";
			STRKEY archives = "Protoss/archives.bmp";
			STRKEY archon = "Protoss/archon.bmp";
			STRKEY archont = "Protoss/archont.bmp";
			STRKEY archont2 = "Protoss/archont2.bmp";
			STRKEY assim = "Protoss/assim.bmp";
			STRKEY biccon_observeratory_ = "Protoss/biccon(observeratory).bmp";
			STRKEY carrier = "Protoss/carrier.bmp";
			STRKEY citadel = "Protoss/citadel.bmp";
			STRKEY corsair = "Protoss/corsair.bmp";
			STRKEY darchn = "Protoss/darchn.bmp";
			STRKEY darchnT = "Protoss/darchnT.bmp";
			STRKEY darchnT2 = "Protoss/darchnT2.bmp";
			STRKEY dragoon = "Protoss/dragoon.bmp";
			STRKEY dtemplar = "Protoss/dtemplar.bmp";
			STRKEY forge = "Protoss/forge.bmp";
			STRKEY forget = "Protoss/forget.bmp";
			STRKEY gateway = "Protoss/gateway.bmp";
			STRKEY gencore = "Protoss/gencore.bmp";
			STRKEY gencoret = "Protoss/gencoret.bmp";
			STRKEY intercep = "Protoss/intercep.bmp";
			STRKEY nexus = "Protoss/nexus.bmp";
			STRKEY pacshad = "Protoss/pacshad.bmp";
			STRKEY passhad = "Protoss/passhad.bmp";
			STRKEY paushad = "Protoss/paushad.bmp";
			STRKEY pb1glow = "Protoss/pb1glow.bmp";
			STRKEY pbaglow_maybeShieldBattery_ = "Protoss/pbaglow(maybeShieldBattery).bmp";
			STRKEY pbaglow = "Protoss/pbaglow.bmp";
			STRKEY pbashad = "Protoss/pbashad.bmp";
			STRKEY pbeshad = "Protoss/pbeshad.bmp";
			STRKEY pcirglow = "Protoss/pcirglow.bmp";
			STRKEY pcishad = "Protoss/pcishad.bmp";
			STRKEY PdaDeath = "Protoss/PdaDeath.bmp";
			STRKEY pdrdeath_DragoonDeath_ = "Protoss/pdrdeath(DragoonDeath).bmp";
			STRKEY pdrShad = "Protoss/pdrShad.bmp";
			STRKEY pfoshad = "Protoss/pfoshad.bmp";
			STRKEY pgashad_Gateway_ = "Protoss/pgashad(Gateway).bmp";
			STRKEY pgaShad = "Protoss/pgaShad.bmp";
			STRKEY pgcShad = "Protoss/pgcShad.bmp";
			STRKEY photon = "Protoss/photon.bmp";
			STRKEY pmarker = "Protoss/pmarker.bmp";
			STRKEY pneglow_Nexus_ = "Protoss/pneglow(Nexus).bmp";
			STRKEY pneshad_Nexus_ = "Protoss/pneshad(Nexus).bmp";
			STRKEY pneShad = "Protoss/pneShad.bmp";
			STRKEY ppbShad = "Protoss/ppbShad.bmp";
			STRKEY ppyshad_Pylon_ = "Protoss/ppyshad(Pylon).bmp";
			STRKEY prism_ArbiterTribunal_ = "Protoss/prism(ArbiterTribunal).bmp";
			STRKEY probe = "Protoss/probe.bmp";
			STRKEY proshad_unknown_ = "Protoss/proshad(unknown).bmp";
			STRKEY psgglow_StargateGlow_ = "Protoss/psgglow(StargateGlow).bmp";
			STRKEY psgshad_Stargate_ = "Protoss/psgshad(Stargate).bmp";
			STRKEY psgShad = "Protoss/psgShad.bmp";
			STRKEY pstshad_RoboticsSupportBay_ = "Protoss/pstshad(RoboticsSupportBay).bmp";
			STRKEY pstShad = "Protoss/pstShad.bmp";
			STRKEY pteshad_Probe_ = "Protoss/pteshad(Probe).bmp";
			STRKEY ptrshad_Unknown_ = "Protoss/ptrshad(Unknown).bmp";
			STRKEY pwashad_Unknown_ = "Protoss/pwashad(Unknown).bmp";
			STRKEY pwaShad = "Protoss/pwaShad.bmp";
			STRKEY pwgShad = "Protoss/pwgShad.bmp";
			STRKEY pxtShad = "Protoss/pxtShad.bmp";
			STRKEY pylon = "Protoss/pylon.bmp";
			STRKEY pzeshad = "Protoss/pzeshad.bmp";
			STRKEY robotic = "Protoss/robotic.bmp";
			STRKEY sapper_Scarab_ = "Protoss/sapper(Scarab).bmp";
			STRKEY sbattery = "Protoss/sbattery.bmp";
			STRKEY scout = "Protoss/scout.bmp";
			STRKEY shuttle = "Protoss/shuttle.bmp";
			STRKEY stargate = "Protoss/stargate.bmp";
			STRKEY stasis_RoboticsSupportBay_ = "Protoss/stasis(RoboticsSupportBay).bmp";
			STRKEY templar = "Protoss/templar.bmp";
			STRKEY texture_BuildingComplete_ = "Protoss/texture(BuildingComplete).bmp";
			STRKEY trilob_Reaver_ = "Protoss/trilob(Reaver).bmp";
			STRKEY warp_FleetBeacon_ = "Protoss/warp(FleetBeacon).bmp";
			STRKEY witness_Observer_ = "Protoss/witness(Observer).bmp";
			STRKEY XelTempl = "Protoss/XelTempl.bmp";
			STRKEY XWarpFir = "Protoss/XWarpFir.bmp";
			STRKEY XWarpGat = "Protoss/XWarpGat.bmp";
			STRKEY zealot = "Protoss/zealot.bmp";
		}

		namespace TERRAN
		{
			STRKEY academy = "Terran/academy.bmp";
			STRKEY academyt = "Terran/academyt.bmp";
			STRKEY battlecr = "Terran/battlecr.bmp";
			STRKEY Bomber_Valkyrie_ = "Terran/Bomber(Valkyrie).bmp";
			STRKEY chemlab_Armory_ = "Terran/chemlab(Armory).bmp";
			STRKEY chemlabt_Armory_ = "Terran/chemlabt(Armory).bmp";
			STRKEY CommandCenter_control_ = "Terran/CommandCenter(control).bmp";
			STRKEY CommandCenter_Prod_controlt_ = "Terran/CommandCenter_Prod(controlt).bmp";
			STRKEY comsat = "Terran/comsat.bmp";
			STRKEY comsatc_Init_ = "Terran/comsatc(Init).bmp";
			STRKEY comsatt = "Terran/comsatt.bmp";
			STRKEY Construction_Large_tbldlrg_ = "Terran/Construction_Large(tbldlrg).bmp";
			STRKEY depot = "Terran/depot.bmp";
			STRKEY depott = "Terran/depott.bmp";
			STRKEY dropship = "Terran/dropship.bmp";
			STRKEY drydockc_ControlTower_ = "Terran/drydockc(ControlTower).bmp";
			STRKEY drydocks_ControlTower_ = "Terran/drydocks(ControlTower).bmp";
			STRKEY drydockt_ControlTower_ = "Terran/drydockt(ControlTower).bmp";
			STRKEY factory = "Terran/factory.bmp";
			STRKEY factoryt = "Terran/factoryt.bmp";
			STRKEY firebat = "Terran/firebat.bmp";
			STRKEY genelab_CovertOps_ = "Terran/genelab(CovertOps).bmp";
			STRKEY genelabc_CovertOps_ = "Terran/genelabc(CovertOps).bmp";
			STRKEY genelabt_CovertOps_ = "Terran/genelabt(CovertOps).bmp";
			STRKEY ghost = "Terran/ghost.bmp";
			STRKEY goliath = "Terran/goliath.bmp";
			STRKEY goliatht = "Terran/goliatht.bmp";
			STRKEY machinec = "Terran/machinec.bmp";
			STRKEY machines = "Terran/machines.bmp";
			STRKEY marine = "Terran/marine.bmp";
			STRKEY medic = "Terran/medic.bmp";
			STRKEY missile = "Terran/missile.bmp";
			STRKEY missilet = "Terran/missilet.bmp";
			STRKEY nukemiss = "Terran/nukemiss.bmp";
			STRKEY nukesilc = "Terran/nukesilc.bmp";
			STRKEY nukesilo = "Terran/nukesilo.bmp";
			STRKEY nukesilt = "Terran/nukesilt.bmp";
			STRKEY phoenix_Wraith_ = "Terran/phoenix(Wraith).bmp";
			STRKEY physics = "Terran/physics.bmp";
			STRKEY physicsc = "Terran/physicsc.bmp";
			STRKEY pillbox_Bunker_ = "Terran/pillbox(Bunker).bmp";
			STRKEY pillboxt_Bunker_ = "Terran/pillboxt(Bunker).bmp";
			STRKEY refinery = "Terran/refinery.bmp";
			STRKEY research_ScienceFacility_ = "Terran/research(ScienceFacility).bmp";
			STRKEY researct_ScienceFacility = "Terran/researct(ScienceFacility.bmp";
			STRKEY scv = "Terran/scv.bmp";
			STRKEY spider = "Terran/spider.bmp";
			STRKEY stank = "Terran/stank.bmp";
			STRKEY stankt = "Terran/stankt.bmp";
			STRKEY starport = "Terran/starport.bmp";
			STRKEY starportt = "Terran/starportt.bmp";
			STRKEY tacshad = "Terran/tacshad.bmp";
			STRKEY tank = "Terran/tank.bmp";
			STRKEY tankt = "Terran/tankt.bmp";
			STRKEY tb1shad = "Terran/tb1shad.bmp";
			STRKEY tb2shad = "Terran/tb2shad.bmp";
			STRKEY tb3shad = "Terran/tb3shad.bmp";
			STRKEY tbarrack = "Terran/tbarrack.bmp";
			STRKEY tbldmed_InConstruction2_ = "Terran/tbldmed(InConstruction2).bmp";
			STRKEY tbldsml_InConstruction3_ = "Terran/tbldsml(InConstruction3).bmp";
			STRKEY tbrshad_Barrcks_ = "Terran/tbrshad(Barrcks).bmp";
			STRKEY tccshad_CommandCenter_ = "Terran/tccshad(CommandCenter).bmp";
			STRKEY tcirglow_Beacon_ = "Terran/tcirglow(Beacon).bmp";
			STRKEY tclshad = "Terran/tclshad.bmp";
			STRKEY tcsshad = "Terran/tcsshad.bmp";
			STRKEY tddshad = "Terran/tddshad.bmp";
			STRKEY tdeshad_SupplyDepot_ = "Terran/tdeshad(SupplyDepot).bmp";
			STRKEY tfashad_Factory_ = "Terran/tfashad(Factory).bmp";
			STRKEY tfbshad = "Terran/tfbshad.bmp";
			STRKEY tghdeath = "Terran/tghdeath.bmp";
			STRKEY tghshad = "Terran/tghshad.bmp";
			STRKEY tglshad = "Terran/tglshad.bmp";
			STRKEY tgoshad = "Terran/tgoshad.bmp";
			STRKEY tmadeath = "Terran/tmadeath.bmp";
			STRKEY tmarker = "Terran/tmarker.bmp";
			STRKEY tmashad = "Terran/tmashad.bmp";
			STRKEY tmeDeath = "Terran/tmeDeath.bmp";
			STRKEY tmeshad = "Terran/tmeshad.bmp";
			STRKEY tmishad = "Terran/tmishad.bmp";
			STRKEY tmsshad = "Terran/tmsshad.bmp";
			STRKEY tnsshad = "Terran/tnsshad.bmp";
			STRKEY tpbshad = "Terran/tpbshad.bmp";
			STRKEY tplshad = "Terran/tplshad.bmp";
			STRKEY treshad = "Terran/treshad.bmp";
			STRKEY trlshad = "Terran/trlshad.bmp";
			STRKEY tsmshad = "Terran/tsmshad.bmp";
			STRKEY tspshad = "Terran/tspshad.bmp";
			STRKEY tstshad = "Terran/tstshad.bmp";
			STRKEY ttashad = "Terran/ttashad.bmp";
			STRKEY tveshad_ScienceVessel_ = "Terran/tveshad(ScienceVessel).bmp";
			STRKEY twpshad_EngineeringBay_ = "Terran/twpshad(EngineeringBay).bmp";
			STRKEY ughost_Kerrigan_ = "Terran/ughost(Kerrigan).bmp";
			STRKEY ughshad_Kerrigan_ = "Terran/ughshad(Kerrigan).bmp";
			STRKEY vulture = "Terran/vulture.bmp";
			STRKEY weaponpl_EngineeringBay_ = "Terran/weaponpl(EngineeringBay).bmp";
			STRKEY weaponpt = "Terran/weaponpt.bmp";
			STRKEY wessel_ScienceVessel_ = "Terran/wessel(ScienceVessel).bmp";
			STRKEY wesselt_ScienceVessel_ = "Terran/wesselt(ScienceVessel).bmp";
		}

		namespace THINGY
		{
			STRKEY VSmoke_geysmok1_ = "thingy/VSmoke(geysmok1).bmp";
			STRKEY VSmokeDeplete_geysmok4_ = "thingy/VSmokeDeplete(geysmok4).bmp";
		}

		namespace WIREFRAME
		{
			STRKEY grpwire = "wireframe/grpwire.bmp";
			STRKEY tranwire = "wireframe/tranwire.bmp";
			STRKEY wirefram = "wireframe/wirefram.bmp";
		}

	}

}
