
#pragma once

//This Code is Automatically generated by CodeGenerator.exe

namespace RES_SHADER

{
	namespace GRAPHICS
	{
		constexpr const char* DEBUG = "Debug.json";
		constexpr const char* PARTICLE = "Particle.json";
		constexpr const char* SCUNIT = "SCUnit.json";
		constexpr const char* STD2D = "STD2D.json";
		constexpr const char* STD2DLIGHT = "STD2DLight.json";
		constexpr const char* TEST = "Test.json";
		constexpr const char* TILEMAPATLAS = "TilemapAtlas.json";
		constexpr const char* TILEMAPCOMPLETE = "TilemapComplete.json";
	}

	namespace COMPUTE
	{
		constexpr const char* SCMAPLOADER = "S_1_C_SCMapLoader.cso";
		constexpr const char* INITALIZE = "S_C_Initalize.cso";
		constexpr const char* PARTICLEBASIC = "S_C_ParticleBasic.cso";
		constexpr const char* PARTICLERAINDROP = "S_C_ParticleRainDrop.cso";
		constexpr const char* SETCOLOR = "S_C_SetColor.cso";
	}
}
