

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr inline const char*
#endif



namespace strKey_Texture
{
	STRKEY beheaded_png = "beheaded.png";
	STRKEY beheaded_n_png = "beheaded_n.png";
	STRKEY Default_png = "Default.png";
	STRKEY Fighter_bmp = "Fighter.bmp";
	STRKEY HOS_bmp = "HOS.bmp";
	STRKEY HOS_png = "HOS.png";
	STRKEY link_png = "link.png";
	STRKEY TILE_bmp = "TILE.bmp";
	namespace NOISE
	{
		STRKEY noise_01_png = "Noise/noise_01.png";
	}

	namespace SC
	{
		namespace BULLET
		{
			STRKEY BlastScan_bmp = "Bullet/BlastScan.bmp";
			STRKEY Circle14_bmp = "Bullet/Circle14.bmp";
			STRKEY DragBull_bmp = "Bullet/DragBull.bmp";
			STRKEY EPBBul_bmp = "Bullet/EPBBul.bmp";
			STRKEY Explo1_bmp = "Bullet/Explo1.bmp";
			STRKEY Gemini_bmp = "Bullet/Gemini.bmp";
			STRKEY Grenades_bmp = "Bullet/Grenades.bmp";
			STRKEY HKS_bmp = "Bullet/HKS.bmp";
			STRKEY Missile_bmp = "Bullet/Missile.bmp";
			STRKEY Parasite_bmp = "Bullet/Parasite.bmp";
			STRKEY PRRIPHIT_bmp = "Bullet/PRRIPHIT.bmp";
			STRKEY PSIBeam_bmp = "Bullet/PSIBeam.bmp";
			STRKEY SCVSpark_bmp = "Bullet/SCVSpark.bmp";
			STRKEY ShockBomb_bmp = "Bullet/ShockBomb.bmp";
			STRKEY Spore2_bmp = "Bullet/Spore2.bmp";
			STRKEY Squib1_bmp = "Bullet/Squib1.bmp";
			STRKEY Squip2_bmp = "Bullet/Squip2.bmp";
		}

		namespace CMDBUTTONS
		{
			STRKEY cmdicons_bmp = "CmdButtons/cmdicons.bmp";
			STRKEY pcmdbtns_bmp = "CmdButtons/pcmdbtns.bmp";
			STRKEY tcmdbtns_bmp = "CmdButtons/tcmdbtns.bmp";
			STRKEY zcmdbtns_bmp = "CmdButtons/zcmdbtns.bmp";
		}

		namespace NEUTRAL
		{
			STRKEY gasorb_bmp = "Neutral/gasorb.bmp";
			STRKEY gassac_bmp = "Neutral/gassac.bmp";
			STRKEY gastank_bmp = "Neutral/gastank.bmp";
			STRKEY geyser_bmp = "Neutral/geyser.bmp";
			STRKEY geyshad_bmp = "Neutral/geyshad.bmp";
			STRKEY min01_bmp = "Neutral/min01.bmp";
			STRKEY min01sha_bmp = "Neutral/min01sha.bmp";
			STRKEY min02_bmp = "Neutral/min02.bmp";
			STRKEY min02sha_bmp = "Neutral/min02sha.bmp";
			STRKEY min03_bmp = "Neutral/min03.bmp";
			STRKEY min03sha_bmp = "Neutral/min03sha.bmp";
		}

		namespace PROTOSS
		{
			STRKEY arbiter_bmp = "Protoss/arbiter.bmp";
			STRKEY archives_bmp = "Protoss/archives.bmp";
			STRKEY archon_bmp = "Protoss/archon.bmp";
			STRKEY archont_bmp = "Protoss/archont.bmp";
			STRKEY archont2_bmp = "Protoss/archont2.bmp";
			STRKEY assim_bmp = "Protoss/assim.bmp";
			STRKEY carrier_bmp = "Protoss/carrier.bmp";
			STRKEY citadel_bmp = "Protoss/citadel.bmp";
			STRKEY corsair_bmp = "Protoss/corsair.bmp";
			STRKEY darchn_bmp = "Protoss/darchn.bmp";
			STRKEY darchnT_bmp = "Protoss/darchnT.bmp";
			STRKEY darchnT2_bmp = "Protoss/darchnT2.bmp";
			STRKEY dragoon_bmp = "Protoss/dragoon.bmp";
			STRKEY dtemplar_bmp = "Protoss/dtemplar.bmp";
			STRKEY forge_bmp = "Protoss/forge.bmp";
			STRKEY forget_bmp = "Protoss/forget.bmp";
			STRKEY gateway_bmp = "Protoss/gateway.bmp";
			STRKEY gencore_bmp = "Protoss/gencore.bmp";
			STRKEY gencoret_bmp = "Protoss/gencoret.bmp";
			STRKEY intercep_bmp = "Protoss/intercep.bmp";
			STRKEY nexus_bmp = "Protoss/nexus.bmp";
			STRKEY pacshad_bmp = "Protoss/pacshad.bmp";
			STRKEY passhad_bmp = "Protoss/passhad.bmp";
			STRKEY paushad_bmp = "Protoss/paushad.bmp";
			STRKEY pb1glow_bmp = "Protoss/pb1glow.bmp";
			STRKEY pbaglow_bmp = "Protoss/pbaglow.bmp";
			STRKEY pbashad_bmp = "Protoss/pbashad.bmp";
			STRKEY pbeshad_bmp = "Protoss/pbeshad.bmp";
			STRKEY pcirglow_bmp = "Protoss/pcirglow.bmp";
			STRKEY pcishad_bmp = "Protoss/pcishad.bmp";
			STRKEY PdaDeath_bmp = "Protoss/PdaDeath.bmp";
			STRKEY pdrShad_bmp = "Protoss/pdrShad.bmp";
			STRKEY pfoshad_bmp = "Protoss/pfoshad.bmp";
			STRKEY pgaShad_bmp = "Protoss/pgaShad.bmp";
			STRKEY pgcShad_bmp = "Protoss/pgcShad.bmp";
			STRKEY photon_bmp = "Protoss/photon.bmp";
			STRKEY pmarker_bmp = "Protoss/pmarker.bmp";
			STRKEY pneShad_bmp = "Protoss/pneShad.bmp";
			STRKEY ppbShad_bmp = "Protoss/ppbShad.bmp";
			STRKEY probe_bmp = "Protoss/probe.bmp";
			STRKEY psgShad_bmp = "Protoss/psgShad.bmp";
			STRKEY pstShad_bmp = "Protoss/pstShad.bmp";
			STRKEY pwaShad_bmp = "Protoss/pwaShad.bmp";
			STRKEY pwgShad_bmp = "Protoss/pwgShad.bmp";
			STRKEY pxtShad_bmp = "Protoss/pxtShad.bmp";
			STRKEY pylon_bmp = "Protoss/pylon.bmp";
			STRKEY pzeshad_bmp = "Protoss/pzeshad.bmp";
			STRKEY robotic_bmp = "Protoss/robotic.bmp";
			STRKEY sbattery_bmp = "Protoss/sbattery.bmp";
			STRKEY scout_bmp = "Protoss/scout.bmp";
			STRKEY shuttle_bmp = "Protoss/shuttle.bmp";
			STRKEY stargate_bmp = "Protoss/stargate.bmp";
			STRKEY templar_bmp = "Protoss/templar.bmp";
			STRKEY XelTempl_bmp = "Protoss/XelTempl.bmp";
			STRKEY XWarpFir_bmp = "Protoss/XWarpFir.bmp";
			STRKEY XWarpGat_bmp = "Protoss/XWarpGat.bmp";
			STRKEY zealot_bmp = "Protoss/zealot.bmp";
		}

		namespace TERRAN
		{
			STRKEY academy_bmp = "Terran/academy.bmp";
			STRKEY academyt_bmp = "Terran/academyt.bmp";
			STRKEY battlecr_bmp = "Terran/battlecr.bmp";
			STRKEY comsat_bmp = "Terran/comsat.bmp";
			STRKEY comsatt_bmp = "Terran/comsatt.bmp";
			STRKEY depot_bmp = "Terran/depot.bmp";
			STRKEY depott_bmp = "Terran/depott.bmp";
			STRKEY dropship_bmp = "Terran/dropship.bmp";
			STRKEY factory_bmp = "Terran/factory.bmp";
			STRKEY factoryt_bmp = "Terran/factoryt.bmp";
			STRKEY firebat_bmp = "Terran/firebat.bmp";
			STRKEY ghost_bmp = "Terran/ghost.bmp";
			STRKEY goliath_bmp = "Terran/goliath.bmp";
			STRKEY goliatht_bmp = "Terran/goliatht.bmp";
			STRKEY machinec_bmp = "Terran/machinec.bmp";
			STRKEY machines_bmp = "Terran/machines.bmp";
			STRKEY marine_bmp = "Terran/marine.bmp";
			STRKEY medic_bmp = "Terran/medic.bmp";
			STRKEY missile_bmp = "Terran/missile.bmp";
			STRKEY missilet_bmp = "Terran/missilet.bmp";
			STRKEY nukemiss_bmp = "Terran/nukemiss.bmp";
			STRKEY nukesilc_bmp = "Terran/nukesilc.bmp";
			STRKEY nukesilo_bmp = "Terran/nukesilo.bmp";
			STRKEY nukesilt_bmp = "Terran/nukesilt.bmp";
			STRKEY physics_bmp = "Terran/physics.bmp";
			STRKEY physicsc_bmp = "Terran/physicsc.bmp";
			STRKEY refinery_bmp = "Terran/refinery.bmp";
			STRKEY researct_ScienceFacility_bmp = "Terran/researct(ScienceFacility.bmp";
			STRKEY scv_bmp = "Terran/scv.bmp";
			STRKEY spider_bmp = "Terran/spider.bmp";
			STRKEY stank_bmp = "Terran/stank.bmp";
			STRKEY stankt_bmp = "Terran/stankt.bmp";
			STRKEY starport_bmp = "Terran/starport.bmp";
			STRKEY starportt_bmp = "Terran/starportt.bmp";
			STRKEY tacshad_bmp = "Terran/tacshad.bmp";
			STRKEY tank_bmp = "Terran/tank.bmp";
			STRKEY tankt_bmp = "Terran/tankt.bmp";
			STRKEY tb1shad_bmp = "Terran/tb1shad.bmp";
			STRKEY tb2shad_bmp = "Terran/tb2shad.bmp";
			STRKEY tb3shad_bmp = "Terran/tb3shad.bmp";
			STRKEY tbarrack_bmp = "Terran/tbarrack.bmp";
			STRKEY tclshad_bmp = "Terran/tclshad.bmp";
			STRKEY tcsshad_bmp = "Terran/tcsshad.bmp";
			STRKEY tddshad_bmp = "Terran/tddshad.bmp";
			STRKEY tfbshad_bmp = "Terran/tfbshad.bmp";
			STRKEY tghdeath_bmp = "Terran/tghdeath.bmp";
			STRKEY tghshad_bmp = "Terran/tghshad.bmp";
			STRKEY tglshad_bmp = "Terran/tglshad.bmp";
			STRKEY tgoshad_bmp = "Terran/tgoshad.bmp";
			STRKEY tmadeath_bmp = "Terran/tmadeath.bmp";
			STRKEY tmarker_bmp = "Terran/tmarker.bmp";
			STRKEY tmashad_bmp = "Terran/tmashad.bmp";
			STRKEY tmeDeath_bmp = "Terran/tmeDeath.bmp";
			STRKEY tmeshad_bmp = "Terran/tmeshad.bmp";
			STRKEY tmishad_bmp = "Terran/tmishad.bmp";
			STRKEY tmsshad_bmp = "Terran/tmsshad.bmp";
			STRKEY tnsshad_bmp = "Terran/tnsshad.bmp";
			STRKEY tpbshad_bmp = "Terran/tpbshad.bmp";
			STRKEY tplshad_bmp = "Terran/tplshad.bmp";
			STRKEY treshad_bmp = "Terran/treshad.bmp";
			STRKEY trlshad_bmp = "Terran/trlshad.bmp";
			STRKEY tsmshad_bmp = "Terran/tsmshad.bmp";
			STRKEY tspshad_bmp = "Terran/tspshad.bmp";
			STRKEY tstshad_bmp = "Terran/tstshad.bmp";
			STRKEY ttashad_bmp = "Terran/ttashad.bmp";
			STRKEY vulture_bmp = "Terran/vulture.bmp";
			STRKEY weaponpt_bmp = "Terran/weaponpt.bmp";
		}

		namespace WIREFRAME
		{
			STRKEY grpwire_bmp = "wireframe/grpwire.bmp";
			STRKEY tranwire_bmp = "wireframe/tranwire.bmp";
			STRKEY wirefram_bmp = "wireframe/wirefram.bmp";
		}

	}

}
