

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr inline const char*
#endif



namespace strKey_Script
{
	STRKEY CScript_CameraMove = "CScript_CameraMove";
	STRKEY CScript_FSM_Attack = "CScript_FSM_Attack";
	STRKEY CScript_FSM_Building_Prod = "CScript_FSM_Building_Prod";
	STRKEY CScript_FSM_Death = "CScript_FSM_Death";
	STRKEY CScript_FSM_Idle = "CScript_FSM_Idle";
	STRKEY CScript_FSM_Move_Ground = "CScript_FSM_Move_Ground";
	STRKEY CScript_FSM_Move_Hover = "CScript_FSM_Move_Hover";
	STRKEY CScript_MainCamSC_InGame = "CScript_MainCamSC_InGame";
	STRKEY CScript_Mineral = "CScript_Mineral";
	STRKEY CScript_MouseCursor = "CScript_MouseCursor";
	STRKEY CScript_SCEntity = "CScript_SCEntity";
	STRKEY CScript_SCUnitVital = "CScript_SCUnitVital";
	STRKEY CScript_TestObj = "CScript_TestObj";
	STRKEY CScript_TilemapUnitLoader = "CScript_TilemapUnitLoader";
	STRKEY CScript_Vespene = "CScript_Vespene";
	STRKEY CScript_VespeneSmoke = "CScript_VespeneSmoke";
}
