

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr inline const char*
#endif



namespace strKey_CShader
{
	STRKEY  = "CCS_SCMapLoader";
}
