
#pragma once

//This Code is Automatically generated by CodeGenerator.exe

namespace SHADERS

{
	namespace GRAPHICS
	{
		constexpr const char* DEBUG = "Debug";
		constexpr const char* PARTICLE = "Particle";
		constexpr const char* STD2D = "STD2D";
		constexpr const char* STD2DLIGHT = "STD2DLight";
		constexpr const char* TEST = "Test";
		constexpr const char* TILEMAPATLAS = "TilemapAtlas";
		constexpr const char* TILEMAPCOMPLETE = "TilemapComplete";
	}

	namespace COMPUTE
	{
		constexpr const char* INITALIZE = "Initalize";
		constexpr const char* PARTICLEBASIC = "ParticleBasic";
		constexpr const char* PARTICLERAINDROP = "ParticleRainDrop";
		constexpr const char* SCMAPLOADER = "SCMapLoader";
		constexpr const char* SETCOLOR = "SetColor";
	}
}
