
#pragma once

#include <string_view>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


namespace RES_TEXTURE
{
	constexpr const std::string_view BEHEADED_PNG = "beheaded.png";
	constexpr const std::string_view BEHEADED_N_PNG = "beheaded_n.png";
	constexpr const std::string_view CORSAIR_BMP = "corsair.bmp";
	constexpr const std::string_view DEFAULT_PNG = "Default.png";
	constexpr const std::string_view FIGHTER_BMP = "Fighter.bmp";
	constexpr const std::string_view HOS_BMP = "HOS.bmp";
	constexpr const std::string_view HOS_PNG = "HOS.png";
	constexpr const std::string_view LINK_PNG = "link.png";
	constexpr const std::string_view MARINE_BMP = "marine.bmp";
	namespace NOISE
	{
		constexpr const std::string_view NOISE_01_PNG = "noise/noise_01.png";
	}
	constexpr const std::string_view TILE_BMP = "TILE.bmp";
	constexpr const std::string_view TRILOB_REAVER__BMP = "trilob(Reaver).bmp";
}