

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr inline const char*
#endif

#include "pch.h"
#include "UserClassInitializer.h"

#include "strKey_Script.h"

#include <Engine/UserClassMgr.h>
#include <Engine/CScript.h>
#define CONSTRUCTOR_T(_Type) UserClassMgr::AddBaseScript(strKey_Script::_Type, Constructor_Script_T<_Type>)

//Script Classes

void UserClassInitializer::InitScript()
{
}