

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#include "pch.h"

#include "UserClassInitializer.h"
#include <Engine/cComMgr.h>
#include "strKey_Component.h"


#include "cCom_Renderer_TilemapSC.h"
#include "cScript_CameraMove.h"
#include "cScript_MainCamSC_InGame.h"
#include "cScript_Mineral.h"
#include "cScript_MouseCursor.h"
#include "cScript_SCEntity.h"
#include "cScript_SCUnitVital.h"
#include "cScript_TestObj.h"
#include "cScript_Vespene.h"
#include "cScript_VespeneSmoke.h"

#define CONSTRUCTOR_T(T) cComMgr::GetInst()->AddComConstructor<T>(strKey_Com::##T)

void UserClassInitializer::InitCom()
{
	CONSTRUCTOR_T(cCom_Renderer_TilemapSC);
	CONSTRUCTOR_T(cScript_CameraMove);
	CONSTRUCTOR_T(cScript_MainCamSC_InGame);
	CONSTRUCTOR_T(cScript_Mineral);
	CONSTRUCTOR_T(cScript_MouseCursor);
	CONSTRUCTOR_T(cScript_SCEntity);
	CONSTRUCTOR_T(cScript_SCUnitVital);
	CONSTRUCTOR_T(cScript_TestObj);
	CONSTRUCTOR_T(cScript_Vespene);
	CONSTRUCTOR_T(cScript_VespeneSmoke);
}