

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#include "pch.h"
#include "UserClassInitializer.h"
#include "strKey_Component.h"
#include <Engine/cUserClassMgr.h>)
#include <Engine/IComponent.h>


#define CONSTRUCTOR_T(T) cUserClassMgr::GetInst()->AddComponentConstructor(strKey_Script::T, Constructor_T<IComponent, T>)

void UserClassInitializer::InitComponent()
{
}