

#pragma once

#include <Engine/define.h>

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#include "pch.h"
#include "UserClassInitializer.h"
#include "strKey_Script.h"
#include <Engine/cUserClassMgr.h>)
#include <Engine/IScript.h>

#include "cScript_CameraMove.h"
#include "cScript_FSM_Attack.h"
#include "cScript_FSM_Building_Prod.h"
#include "cScript_FSM_Death.h"
#include "cScript_FSM_Idle.h"
#include "cScript_FSM_Move_Ground.h"
#include "cScript_FSM_Move_Hover.h"
#include "cScript_MainCamSC_InGame.h"
#include "cScript_Mineral.h"
#include "cScript_MouseCursor.h"
#include "cScript_SCEntity.h"
#include "cScript_SCUnitVital.h"
#include "cScript_TestObj.h"
#include "cScript_TilemapSC.h"
#include "cScript_Vespene.h"
#include "cScript_VespeneSmoke.h"

#define CONSTRUCTOR_T(T) cUserClassMgr::GetInst()->AddScriptConstructor(strKey_Script::T, Constructor_Script_T<T>)

void UserClassInitializer::InitScript()
{
	CONSTRUCTOR_T(cScript_CameraMove);
	CONSTRUCTOR_T(cScript_FSM_Attack);
	CONSTRUCTOR_T(cScript_FSM_Building_Prod);
	CONSTRUCTOR_T(cScript_FSM_Death);
	CONSTRUCTOR_T(cScript_FSM_Idle);
	CONSTRUCTOR_T(cScript_FSM_Move_Ground);
	CONSTRUCTOR_T(cScript_FSM_Move_Hover);
	CONSTRUCTOR_T(cScript_MainCamSC_InGame);
	CONSTRUCTOR_T(cScript_Mineral);
	CONSTRUCTOR_T(cScript_MouseCursor);
	CONSTRUCTOR_T(cScript_SCEntity);
	CONSTRUCTOR_T(cScript_SCUnitVital);
	CONSTRUCTOR_T(cScript_TestObj);
	CONSTRUCTOR_T(cScript_TilemapSC);
	CONSTRUCTOR_T(cScript_Vespene);
	CONSTRUCTOR_T(cScript_VespeneSmoke);
}