#include "S_H_Register.hlsli"


#define REGISLOT_u_TEXTURERW_SETCOLOR			REGISTER_SLOT(u, 0)
#define REGISLOT_u_SBUFFERRW_SETCOLOR			REGISTER_SLOT(u, 1)

#define SETCOLOR_THREADS_X 32
#define SETCOLOR_THREADS_Y 32
#define SETCOLOR_THREADS_Z 1
